version: '3'
services:
  postgres:
    image: postgres
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgres/data
  web:
    build: .
    ports:
      - "5000:5000" 
volumes:
  data: {}
